<?php
/**
 * PineGrap - Enterprise Website Platform
 *
 * Originally developed as LiveSite by Camelback Web Architects.
 * Since 2017, maintained and evolved by Erdal Güral (Kodpen) under the name PineGrap.
 * The final LiveSite update (2019) has been integrated into PineGrap.
 * LiveSite remains available as a separate downloadable legacy version.
 *
 * @author      Camelback Web Architects
 *              Erdal Güral (Kodpen)
 * @link        https://livesite.com
 *              https://kodpen.com
 * @copyright   2001–2019 Camelback Consulting, Inc.
 *              2016–2026 Kodpen
 * @license     https://opensource.org/licenses/mit-license.html MIT License
 */

include('init.php');
$user = validate_user();
validate_ecommerce_access($user);

validate_token_field();

include_once('liveform.class.php');

// if at least one order was selected
if ($_POST['orders']) {

    switch ($_POST['action']) {

        case 'export_orders_for_parasut':
            //This feature is used for invoicing orders via the parasut.com application with the help of a draft excel file.
            /** Include PHPExcel */
            require_once dirname(__FILE__) . '/assets/phpexcel/PHPExcel.php';

            $objPHPExcel1 = new PHPExcel();
            // Create new PHPExcel object with template (1)
            $objPHPExcel1 = PHPExcel_IOFactory::load("assets/phpexcel/templates/parasut_satis_faturalari.xlsx");
            // Create new PHPExcel object with template (2)
            $objPHPExcel2 = PHPExcel_IOFactory::load("assets/phpexcel/templates/parasut_musteri_ve_tedarikciler.xlsx");

            $borderstyleArray = array('borders' => array('allborders' => array('style' => PHPExcel_Style_Border::BORDER_THIN,'color' => array('rgb' => 'b8b8b8'))));
            $organization_name = '';
            // if ORGANIZATION_NAME defined and ORGANIZATION_NAME is not empty, use it as $organization_name 
            if(defined('ORGANIZATION_NAME') && ORGANIZATION_NAME != ''){
                $organization_name = ORGANIZATION_NAME;
            }else{
                //else ORGANIZATION_NAME  empty or not defined.
                // use HOSTNAME_SETTING as $organization_name
                if(defined('HOSTNAME_SETTING')){
                    $organization_name = HOSTNAME_SETTING;
                }else{
                    //else HOSTNAME_SETTING empty or not defined.
                    // use this.
                    $organization_name = 'Pinegrap CMS';
                }
            }


            // Set document properties (1)
            $objPHPExcel1->getProperties()
            ->setCreator($user['email_address'])
            ->setLastModifiedBy($user['email_address'])
            ->setTitle("Pinegrap - Parasut Invoice import file")
            ->setSubject("Pinegrap Orders E-Invoice Document output for parasut")
            ->setDescription("This file is auto-generated by the Pinegrap Software based on user selections and uses a template.")
            ->setKeywords("Pinegrap")
            ->setCompany("Kodpen (www.kodpen.com)")
            ->setCategory("fatura");

            // Set document properties (2)
            $objPHPExcel2->getProperties()
            ->setCreator($user['email_address'])
            ->setLastModifiedBy($user['email_address'])
            ->setTitle("Pinegrap - Parasut Customer & Suppliers import file")
            ->setSubject("Pinegrap Orders Contacts Document output for parasut")
            ->setDescription("This file is auto-generated by the Pinegrap Software based on user selections and uses a template.")
            ->setKeywords("Pinegrap")
            ->setCompany("Kodpen (www.kodpen.com)")
            ->setCategory("Kişiler");

            //our templates start from line 4.
            //count with different verables because customer sheet uses 1 line but invoice more lines for products.
            $i_obj_1 = 4;
            $i_obj_2 = 4;

            //count orders.
            $number_of_orders = 0;
            foreach ($_POST['orders'] as $order_id) {
                //$objPHPExcel1 is Invoice sheet.
                //$objPHPExcel2 is Customers sheet.
                //we generate 2 file to merge, parasut wants first customer information before complete E-Invoice.
            
                //get order information
                $query = "SELECT
                    orders.id,
                    orders.billing_first_name,
                    orders.billing_last_name,
                    orders.status,
                    orders.order_number,
                    user.user_username as username,
                    orders.total,
                    orders.order_date,
                    orders.billing_email_address,
                    orders.billing_company,
                    orders.billing_phone_number,
                    orders.billing_fax_number,
                    orders.billing_address_1,
                    orders.billing_address_2,
                    orders.billing_zip_code,
                    orders.billing_city,
                    orders.billing_state,
                    orders.custom_field_1,
                    orders.custom_field_2,
                    orders.surcharge,
                    orders.shipping,
                    orders.payment_installment,
                    orders.installment_charges,
                    contacts.tax_number AS contact_tax_number
                FROM orders
                LEFT JOIN user ON orders.user_id = user.user_id
                LEFT JOIN contacts ON orders.contact_id = contacts.id
                WHERE ((orders.status = 'complete') OR (orders.status = 'exported'))
                AND orders.id = '" . escape($order_id) . "'";
                $result=mysqli_query(db::$con, $query) or output_error('Query failed.');
                $row = mysqli_fetch_array($result);
                $billing_first_name = $row['billing_first_name'];
                $billing_last_name = $row['billing_last_name'];
                $order_date = $row['order_date'];
                $order_number = $row['order_number'];
                $username = $row['username'];
                $total = $row['total'];
                $billing_email_address = $row['billing_email_address'];
                $billing_company = $row['billing_company'];
                $billing_phone_number = $row['billing_phone_number'];
                $billing_fax_number = $row['billing_fax_number'];
                $billing_address_1 = $row['billing_address_1'];
                $billing_address_2 = $row['billing_address_2'];
                $billing_zip_code = $row['billing_zip_code'];
                $billing_city = $row['billing_city'];
                $billing_state = $row['billing_state'];
                $custom_field_1 = $row['custom_field_1'];
                $custom_field_2 = $row['custom_field_2'];
                $payment_installment = $row['payment_installment'];
                $installment_charges = $row['installment_charges'];
                $surcharge = $row['surcharge'];
                $shipping = $row['shipping'];
                 

                $customer_billing_name = mb_convert_case(mb_strtolower($billing_first_name . ' ' . $billing_last_name,'utf8'), MB_CASE_TITLE, "UTF-8");
                $billing_combined_address = $billing_address_1 . $billing_address_2 . ' ' . $billing_zip_code;
                //PARASUT_TC_IN_FIELD republic of turkey identification number
                //this is show us where we get republic of turkey identification number (its not required but easy with it.)
                $identification_number = '';
                if( defined('PARASUT_TC_IN_FIELD')  && PARASUT_TC_IN_FIELD != 'do not use'){
                    if(PARASUT_TC_IN_FIELD == 'custom_field_1'){
                        $identification_number = $custom_field_1;
                    }elseif(PARASUT_TC_IN_FIELD == 'custom_field_2'){
                        $identification_number = $custom_field_2;
                    }elseif(PARASUT_TC_IN_FIELD == 'tax_number'){
                        $identification_number = $row['contact_tax_number'];
                    }
                }
                $product_tax_rate = $_POST['tax_rate_for_parasut'];
                $product_tax_rate_included = $_POST['tax_rate_included_for_parasut'];
                //if tax is empty than its 0
                if($product_tax_rate == ''){
                    $product_tax_rate = 0;
                }

                $objPHPExcel2->getActiveSheet()
                ->setCellValue('A'. $i_obj_2 ,$customer_billing_name)                                               //A FİRMA ADI MÜŞTERİ ÜNVANI*
                                                                                                                    //B KISA ADI	
                ->setCellValue('C' . $i_obj_2,"M")                                                                  //C MÜŞTERİ/TEDARİKÇİ*	
                ->setCellValue('D' . $i_obj_2,$billing_email_address)                                               //D E-POSTA	
                ->setCellValue('E' . $i_obj_2,"Pinegrap CMS")                                                       //E KATEGORİ	
                ->setCellValue('F' . $i_obj_2,$billing_combined_address)                                            //F ADRES	
                ->setCellValue('G' . $i_obj_2,$billing_city)                                                        //G İLÇE	
                ->setCellValue('H' . $i_obj_2,$billing_state)                                                       //H İL	
                ->setCellValueExplicit('I' . $i_obj_2,$billing_phone_number,PHPExcel_Cell_DataType::TYPE_STRING)    //I TELEFON	
                ->setCellValueExplicit('J' . $i_obj_2,$billing_fax_number,PHPExcel_Cell_DataType::TYPE_STRING)      //J FAKS	
                                                                                                                    //K VERGİ DAİRESİ	
                                                                                                                    //L VERGİ NUMARASI	
                ->setCellValue('M' . $i_obj_2,$identification_number);                                              //M TC KİMLİK NO	
                                                                                                                    //N AÇILIŞ BAKİYESİ TARİHİ 
                                                                                                                    //P AÇILIŞ BAKİYESİ DÖVİZ CİNSİ	
                                                                                                                    //P AÇILIŞ BAKİYESİ TUTARI	
                                                                                                                    //Q AÇILIŞ BAKİYESİ TÜRÜ
                //Set Border color and style
                $objPHPExcel2->getActiveSheet()->getStyle('A' . $i_obj_2 . ':Q' . $i_obj_2)->applyFromArray($borderstyleArray);
                //Align all lines to left.
                $objPHPExcel2->getActiveSheet()->getStyle('A' . $i_obj_2 . ':Q' . $i_obj_2)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
                
                $i_obj_2++;

                $objPHPExcel1->getActiveSheet()
                ->setCellValue('A'. $i_obj_1 ,$customer_billing_name)                                               //A | MÜŞTERİ ÜNVANI*	           
                ->setCellValue('B' . $i_obj_1, $organization_name . ' - ' . $order_number)                          //B | FATURA AÇIKLAMASI	                                
                ->setCellValue('C' . $i_obj_1,PHPExcel_Shared_Date::PHPToExcel(date('j.m.Y H:i',time())))           //C | FATURA TARİHİ*           
                                                                                                                    //D | DÖVİZ CİNSİ	    
                                                                                                                    //E | DÖVİZ KURU	        
                ->setCellValue('F' . $i_obj_1,PHPExcel_Shared_Date::PHPToExcel(date('j.m.Y H:i',$order_date)))      //F | VADE TARİHİ(Order Date)         
                                                                                                                    //G | TAHSİLAT TL KARŞILIĞI	        
                ->setCellValue('H' . $i_obj_1,"Fatura")                                                             //H | FATURA TÜRÜ	        
                                                                                                                    //I | FATURA SERİ	    
                                                                                                                    //J | FATURA SIRANO	    
                ->setCellValue('K' . $i_obj_1,"Pinegrap CMS");                                                      //K | KATEGORİ	   

                $objPHPExcel1->getActiveSheet()->getStyle('C' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_PARASUT);
                $objPHPExcel1->getActiveSheet()->getStyle('F' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_PARASUT);

                $query = "SELECT
                    order_items.product_id as product_id,
                    order_items.price as price,
                    order_items.product_name as product_name,
                    order_items.quantity as quantity,
                    order_items.offer_action_id as offer_action_id
                FROM order_items
                WHERE order_id = '" . escape($order_id) . "'";

                //align all lines to left
                $objPHPExcel1->getActiveSheet()->getStyle('A' . $i_obj_1 . ':S' . $i_obj_1)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);

                $result = mysqli_query(db::$con, $query) or output_error('Query failed.');
                if($result){
                    while($order_item = mysqli_fetch_assoc($result)) {
                        $order_item_product_id = $order_item['product_id'];
                        $price = $order_item['price'];
                        $product_name = $order_item['product_name'];
                        $quantity = $order_item['quantity'];
                        $offer_action_id = $order_item['offer_action_id'];
                        
                        $product_discount = 0;
                        
                        //if product name is not empty use it
                        if(db("SELECT short_description FROM products WHERE id = '" . escape($order_item_product_id) . "'") != ''){
                            $product_name = db("SELECT short_description FROM products WHERE id = '" . escape($order_item_product_id) . "'");
                        }



                        //if tax_rate_included_for_parasut checked
                        if($product_tax_rate_included == 1){
                            //deduct tax rate from product price, because parasut require tax, calculates and adds to the price.
                            //Pinegrap calculates tax by customer tax zone and add it to order and order can contain taxed product or untaxed.
                            if($product_tax_rate > 0){
                                $price = $price / (1+$product_tax_rate/100); //tax deducted product price  = price / (1+tax rate /100)
                            }
                        }

                        // start from 4th line
                        //Set Data
                        $objPHPExcel1->getActiveSheet()
                        ->setCellValue('L' . $i_obj_1,$product_name)                    //L | HİZMET/ÜRÜN*	                    
                                                                                        //M | HİZMET/ÜRÜN AÇIKLAMASI	                            
                                                                                        //N | ÇIKIŞ DEPOSU	    
                        ->setCellValue('O' . $i_obj_1,$quantity)                        //O | MİKTAR*	    
                        ->setCellValue('P' . $i_obj_1, ($price / 100) )                 //P | BİRİM FİYATI*	        
                        ->setCellValue('Q' . $i_obj_1, ($product_discount / 100))       //Q | İNDİRİM TUTARI	    
                        ->setCellValue('R' . $i_obj_1,$product_tax_rate)                //R | KDV ORANI*	        
                        ->setCellValue('S' . $i_obj_1,0);                               //S | ÖİV ORANI  

                        //format lines
                        $objPHPExcel1->getActiveSheet()->getStyle('A' . $i_obj_1 . ':T' . $i_obj_1)->applyFromArray($borderstyleArray);
                        $objPHPExcel1->getActiveSheet()->getStyle('P' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT);
                        $objPHPExcel1->getActiveSheet()->getStyle('Q' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT);
                        $objPHPExcel1->getActiveSheet()->getStyle('S' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT);
                        $objPHPExcel1->getActiveSheet()->getStyle('R' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT1);
                        
                        //align all lines to left
                        $objPHPExcel1->getActiveSheet()->getStyle('A' . $i_obj_1 . ':S' . $i_obj_1)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
                        $i_obj_1++;
                    }

                }else{
                    $objPHPExcel1->getActiveSheet()->getStyle('A' . $i_obj_1 . ':S' . $i_obj_1)->applyFromArray($borderstyleArray);
                    
                    $i_obj_1++;
                }
                //if installment for this order, add it in a new row as a product.
                if($installment_charges){
                    if($product_tax_rate > 0){
                        $installment_charges = $installment_charges / (1+$product_tax_rate/100); //tax deducted product price  = price / (1+tax rate /100)
                    }
                    $objPHPExcel1->getActiveSheet()
                    ->setCellValue('L' . $i_obj_1,lang('Order installment fee') . ' (' . $payment_installment . 'x)')       //L | HİZMET/ÜRÜN*	                    
                                                                                    //M | HİZMET/ÜRÜN AÇIKLAMASI	                            
                                                                                    //N | ÇIKIŞ DEPOSU	    
                    ->setCellValue('O' . $i_obj_1,'1')                              //O | MİKTAR*	    
                    ->setCellValue('P' . $i_obj_1, ($installment_charges / 100) )   //P | BİRİM FİYATI*	        
                    ->setCellValue('Q' . $i_obj_1, 0)                               //Q | İNDİRİM TUTARI	    
                    ->setCellValue('R' . $i_obj_1,$product_tax_rate)                //R | KDV ORANI*	        
                    ->setCellValue('S' . $i_obj_1,0);                               //S | ÖİV ORANI  

                    //format lines
                    $objPHPExcel1->getActiveSheet()->getStyle('A' . $i_obj_1 . ':S' . $i_obj_1)->applyFromArray($borderstyleArray);
                    $objPHPExcel1->getActiveSheet()->getStyle('P' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT);
                    $objPHPExcel1->getActiveSheet()->getStyle('Q' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT);
                    $objPHPExcel1->getActiveSheet()->getStyle('S' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT);
                    $objPHPExcel1->getActiveSheet()->getStyle('R' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT1);
                    
                    //align all lines to left
                    $objPHPExcel1->getActiveSheet()->getStyle('A' . $i_obj_1 . ':S' . $i_obj_1)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
                    $i_obj_1++;
                } 
                //if shipping for for this order, add it in a new row as a product.
                if($shipping){
                    if($product_tax_rate > 0){
                        $shipping = $shipping / (1+$product_tax_rate/100); //tax deducted product price  = price / (1+tax rate /100)
                    }
                    $objPHPExcel1->getActiveSheet()
                    ->setCellValue('L' . $i_obj_1,lang('Order shipping fee') )      //L | HİZMET/ÜRÜN*	                    
                                                                                    //M | HİZMET/ÜRÜN AÇIKLAMASI	                            
                                                                                    //N | ÇIKIŞ DEPOSU	    
                    ->setCellValue('O' . $i_obj_1,'1')                              //O | MİKTAR*	    
                    ->setCellValue('P' . $i_obj_1, ($shipping / 100) )              //P | BİRİM FİYATI*	        
                    ->setCellValue('Q' . $i_obj_1, 0)                               //Q | İNDİRİM TUTARI	    
                    ->setCellValue('R' . $i_obj_1,$product_tax_rate)                //R | KDV ORANI*	        
                    ->setCellValue('S' . $i_obj_1,0);                               //S | ÖİV ORANI  

                    //format lines
                    $objPHPExcel1->getActiveSheet()->getStyle('A' . $i_obj_1 . ':S' . $i_obj_1)->applyFromArray($borderstyleArray);
                    $objPHPExcel1->getActiveSheet()->getStyle('P' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT);
                    $objPHPExcel1->getActiveSheet()->getStyle('Q' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT);
                    $objPHPExcel1->getActiveSheet()->getStyle('S' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT);
                    $objPHPExcel1->getActiveSheet()->getStyle('R' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT1);
                    
                    //align all lines to left
                    $objPHPExcel1->getActiveSheet()->getStyle('A' . $i_obj_1 . ':S' . $i_obj_1)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
                    $i_obj_1++;
                }
                //if surcharge for for this order, add it in a new row as a product.
                if($surcharge){
                    if($product_tax_rate > 0){
                        $surcharge = $surcharge / (1+$product_tax_rate/100); //tax deducted product price  = price / (1+tax rate /100)
                    }
                    $objPHPExcel1->getActiveSheet()
                    ->setCellValue('L' . $i_obj_1,lang('Order Surcharge fee') )      //L | HİZMET/ÜRÜN*	                    
                                                                                    //M | HİZMET/ÜRÜN AÇIKLAMASI	                            
                                                                                    //N | ÇIKIŞ DEPOSU	    
                    ->setCellValue('O' . $i_obj_1,'1')                              //O | MİKTAR*	    
                    ->setCellValue('P' . $i_obj_1, ($surcharge / 100) )             //P | BİRİM FİYATI*	        
                    ->setCellValue('Q' . $i_obj_1, 0)                               //Q | İNDİRİM TUTARI	    
                    ->setCellValue('R' . $i_obj_1,$product_tax_rate)                //R | KDV ORANI*	        
                    ->setCellValue('S' . $i_obj_1,0);                               //S | ÖİV ORANI  

                    //format lines
                    $objPHPExcel1->getActiveSheet()->getStyle('A' . $i_obj_1 . ':S' . $i_obj_1)->applyFromArray($borderstyleArray);
                    $objPHPExcel1->getActiveSheet()->getStyle('P' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT);
                    $objPHPExcel1->getActiveSheet()->getStyle('Q' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT);
                    $objPHPExcel1->getActiveSheet()->getStyle('S' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT);
                    $objPHPExcel1->getActiveSheet()->getStyle('R' . $i_obj_1)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_NUMBER_COMMA_SEPARATED_PARASUT1);
                    
                    //align all lines to left
                    $objPHPExcel1->getActiveSheet()->getStyle('A' . $i_obj_1 . ':S' . $i_obj_1)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
                    $i_obj_1++;
                }



                db("UPDATE orders SET parasut_exported = 1 WHERE id = '" . escape($order_id) . "'");
                $number_of_orders++;
            }

            //Generate a date for zip and file names.
            $output_date = date('Y_m_d_H_i_s',time());
            //location to use as temporary directory.
            $temps_location = 'assets/phpexcel/temps/';
            //generate parasut temp folder name.
            $temp_folder_name = 'parasut_' . $output_date;
            //check if temp folder is exist else generate one for save excel files inside.
            if (!file_exists($temps_location . $temp_folder_name)) {
                mkdir($temps_location . $temp_folder_name, 0777, true);
            }

            // Set active sheet index to the first sheet, so Excel opens this as the first sheet and save it to temp directory
            $objPHPExcel1->setActiveSheetIndex(0);
            $objWriter1 = PHPExcel_IOFactory::createWriter($objPHPExcel1, 'Excel2007');
            $objWriter1->save($temps_location . $temp_folder_name . '/parasut_satis_faturalari_' . $output_date . '.xlsx');
            // Set active sheet index to the first sheet, so Excel opens this as the first sheet and save it to temp directory
            $objPHPExcel2->setActiveSheetIndex(0);
            $objWriter2 = PHPExcel_IOFactory::createWriter($objPHPExcel2, 'Excel2007');
            $objWriter2->save($temps_location . $temp_folder_name . '/parasut_musteri_ve_tedarikciler_' . $output_date . '.xlsx');

			$dir = $temps_location.$temp_folder_name;
			$zip_file = $temps_location.$temp_folder_name.'/'.$temp_folder_name.'.zip';			
			// Get real path for our folder
			$rootPath = realpath($dir);
			
			// Initialize archive object
			$zip = new ZipArchive();
			$zip->open($zip_file, ZipArchive::CREATE | ZipArchive::OVERWRITE);
			
			// Create recursive directory iterator
			/** @var SplFileInfo[] $files */
			$files = new RecursiveIteratorIterator(
				new RecursiveDirectoryIterator($rootPath),
				RecursiveIteratorIterator::LEAVES_ONLY
			);
			
			foreach ($files as $name => $file)
			{
				// Skip directories (they would be added automatically)
				if (!$file->isDir())
				{
					// Get real and relative path for current file
					$filePath = $file->getRealPath();
					$relativePath = substr($filePath, strlen($rootPath) + 1);
			
					// Add current file to archive
					$zip->addFile($filePath, $relativePath);
				}
			}
			// Zip archive will be created only after closing object
			$zip->close();
			header('Content-Description: File Transfer');
			header("Content-type: application/zip"); 
			header("Content-Disposition: attachment; filename=$temp_folder_name.zip");
			header("Content-length: " . filesize($zip_file));
			header("Pragma: no-cache"); 
			header("Expires: 0"); 
			$handle = fopen($zip_file, "rb");
			while (!feof($handle)){
				echo fread($handle, 8192);
			}
			fclose($handle);

            //remove temps folder and everything inside it.
			$dir = $temps_location;
			$it = new RecursiveDirectoryIterator($dir, RecursiveDirectoryIterator::SKIP_DOTS);
			$files = new RecursiveIteratorIterator($it,
			         RecursiveIteratorIterator::CHILD_FIRST);
			foreach($files as $file) {
			    if ($file->isDir()){
			        rmdir($file->getRealPath());
			    } else {
			        unlink($file->getRealPath());
			    }
			}
			rmdir($dir);
           

            // if at least one order was exported, then log activity
            if ($number_of_orders > 0) {
                log_activity(lang(array('string'=>'{var:1} order(s) were exported for parasut.com','vars'=>array(number_format($number_of_orders)) )) , $_SESSION['sessionusername']);
            }
            $liveform_view_orders = new liveform('view_orders');
            $liveform_view_orders->add_notice(lang(array('string'=>'{var:1} order(s) and the information of the contact(s) they are connected to have been exported with {var:2}.zip file.','vars'=>array(number_format($number_of_orders),$temp_folder_name) )) );
            
            break;
        // if the user selected to remove card data for orders, then do that
        case 'remove_card_data':
            // loop through all selected orders
            foreach ($_POST['orders'] as $order_id) {
                // get credit card data for order
                $query = 
                    "SELECT
                        card_number,
                        card_verification_number
                    FROM orders
                    WHERE id = '" . escape($order_id) . "'";
                $result = mysqli_query(db::$con, $query) or output_error('Query failed.');
                $row = mysqli_fetch_assoc($result);
                $card_number = $row['card_number'];
                $card_verification_number = $row['card_verification_number'];
                
                // if there is a credit card number and the credit card number is not protected or there is a card verification number and it is not protected, then continue to remove credit card data
                if (
                    (($card_number != '') && (mb_substr($card_number, 0, 1) != '*'))
                    || (($card_verification_number != '') && (mb_substr($card_verification_number, 0, 1) != '*'))
                ) {
                    // if the credit card number is not already protected, then protect card number
                    if (mb_substr($card_number, 0, 1) != '*') {
                        // if the credit card number is encrypted, then decrypt it and then protect it
                        if (mb_strlen($card_number) > 16) {
                            // if encryption is enabled, then decrypt the credit card number
                            if (
                                (defined('ENCRYPTION_KEY') == TRUE)
                                && (extension_loaded('mcrypt') == TRUE)
                                && (in_array('rijndael-256', mcrypt_list_algorithms()) == TRUE)
                            ) {
                                $card_number = decrypt_credit_card_number($card_number, ENCRYPTION_KEY);
                                
                                // if the credit card number is not numeric, then there was a decryption error, so clear credit card number
                                if (is_numeric($card_number) == FALSE) {
                                    $card_number = '';
                                    
                                // else the decryption was successful, so protect credit card number
                                } else {
                                    $card_number = protect_credit_card_number($card_number);
                                }
                                
                            // else encryption is disabled, so clear credit card number
                            } else {
                                $card_number = '';
                            }
                            
                        // else the credit card number is not encrypted, so just protect it
                        } else {
                            $card_number = protect_credit_card_number($card_number);
                        }
                    }
                    
                    // if the card verification number is not already protected, then protect it
                    if (mb_substr($card_verification_number, 0, 1) != '*') {
                        $card_verification_number = protect_card_verification_number($card_verification_number);
                    }
                    
                    // update credit card data for order
                    $query =
                        "UPDATE orders
                        SET
                            card_number = '" . escape($card_number) . "',
                            card_verification_number = '" . escape($card_verification_number) . "'
                        WHERE id = '" . escape($order_id) . "'";
                    $result = mysqli_query(db::$con, $query) or output_error('Query failed.');
                    
                    $number_of_orders++;
                }
            }
            
            // if credit card data was removed from more than 0 orders, then log activity
            if ($number_of_orders > 0) {
                log_activity(lang(array('string'=>'Card data was removed from {var:1} order(s).','vars'=>array(number_format($number_of_orders)))), $_SESSION['sessionusername']);
            }
            
            $liveform_view_orders = new liveform('view_orders');
            $liveform_view_orders->add_notice( lang(array('string'=>'Card data was removed from {var:1} order(s).','vars'=>array(number_format($number_of_orders)))) );
            
            break;
            
        // if orders are being deleted
        case 'delete':

            require_once(dirname(__FILE__) . '/delete_order.php');

            foreach ($_POST['orders'] as $order_id) {

                $order['id'] = $order_id;

                $response = delete_order(array('order' => $order));

                if ($response['status'] == 'error') {
                    output_error(h($response['message']));
                }

                $number_of_orders++;
            }
            
            // if at least one order was deleted, then log activity
            if ($number_of_orders > 0) {
                log_activity(lang(array('string'=>'{var:1} order(s) were deleted','vars'=>array(number_format($number_of_orders)) )) , $_SESSION['sessionusername']);
            }
            
            $liveform_view_orders = new liveform('view_orders');
            $liveform_view_orders->add_notice(lang(array('string'=>'{var:1} order(s) were deleted','vars'=>array(number_format($number_of_orders)) )) );

            break;

        // ── Bulk cancel selected orders ────────────────────────────────
        // Admin-only path (this script already gated by validate_user +
        // validate_ecommerce_access on entry). We loop sequentially so
        // each call's Iyzipay refund attempt + email send is atomic and
        // we can surface a per-outcome counter to the operator. Errors
        // do NOT halt the loop — they accumulate in counters so a single
        // bad row (already shipped, already cancelled, etc.) doesn't
        // strand the remaining selections.
        case 'cancel':

            // validate_user() returns the PK under "id" — NOT "user_id" (that
            // is the raw column name, used by the api.php/apps.php auth path).
            // Reading the wrong key silently recorded cancelled_by = 0, which
            // reports interpret as "customer self-service".
            $cancel_admin_user_id = (int) (isset($user['id']) ? $user['id'] : 0);
            $bulk_cancelled = 0;
            $bulk_skipped_already = 0;
            $bulk_skipped_shipped = 0;
            $bulk_failed = 0;

            foreach ($_POST['orders'] as $order_id) {
                $res = process_order_cancellation(
                    (int) $order_id,
                    '',                       // operator-typed reason not collected for bulk
                    true,                     // is_admin
                    $cancel_admin_user_id
                );
                switch ($res['status']) {
                    case 'success': $bulk_cancelled++;       break;
                    case 'already': $bulk_skipped_already++; break;
                    case 'shipped': $bulk_skipped_shipped++; break;
                    default:        $bulk_failed++;          break;
                }
            }

            if ($bulk_cancelled > 0) {
                log_activity(
                    lang(array(
                        'string' => '{var:1} order(s) were cancelled',
                        'vars'   => array(number_format($bulk_cancelled)),
                    )),
                    $_SESSION['sessionusername']
                );
            }

            $liveform_view_orders = new liveform('view_orders');
            $liveform_view_orders->add_notice(
                lang(array(
                    'string' => '{var:1} order(s) were cancelled',
                    'vars'   => array(number_format($bulk_cancelled)),
                ))
            );
            if ($bulk_skipped_already > 0) {
                $liveform_view_orders->add_warning(
                    lang(array(
                        'string' => '{var:1} order(s) were already cancelled and skipped',
                        'vars'   => array(number_format($bulk_skipped_already)),
                    ))
                );
            }
            if ($bulk_skipped_shipped > 0) {
                $liveform_view_orders->add_warning(
                    lang(array(
                        'string' => '{var:1} order(s) had already shipped and were skipped',
                        'vars'   => array(number_format($bulk_skipped_shipped)),
                    ))
                );
            }
            if ($bulk_failed > 0) {
                $liveform_view_orders->add_error(
                    lang(array(
                        'string' => '{var:1} order(s) could not be cancelled',
                        'vars'   => array(number_format($bulk_failed)),
                    ))
                );
            }

            break;
    }
}

header('Location: ' . URL_SCHEME . HOSTNAME . PATH . SOFTWARE_DIRECTORY . '/view_orders.php');